#!/usr/bin/env node
// Bundles the text assets the Worker serves (SDK, guide, web page JS/CSS)
// into src/generated/assets.ts so both wrangler (esbuild) and vitest (vite)
// can import them without loader-specific configuration.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const assets = {
  SDK_JS: "src/sdk.js",
  GUIDE_MD: "src/guide.md",
  DASHBOARD_JS: "src/dashboard/dashboard.js",
  FORMELAB_CSS: "src/dashboard/formelab.css",
  THEME_JS: "src/dashboard/theme.js",
  SITE_JS: "src/dashboard/site.js",
  CONSENT_JS: "src/dashboard/consent.js",
  SKILL_MD: "skill/SKILL.md",
};

export function generateAssets() {
  let out = "// Generated by scripts/gen-assets.mjs. Do not edit.\n";
  for (const [name, rel] of Object.entries(assets)) {
    out += `export const ${name} = ${JSON.stringify(readFileSync(join(root, rel), "utf8"))};\n`;
  }
  const target = join(root, "src/generated/assets.ts");
  mkdirSync(dirname(target), { recursive: true });
  let previous = "";
  try {
    previous = readFileSync(target, "utf8");
  } catch {}
  if (previous !== out) writeFileSync(target, out);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) generateAssets();
